import Foundation

/// Oberflächensprache: Deutsch, wenn macOS die App auf Deutsch zeigt, sonst Englisch.
/// Die deutschen Texte im Code sind zugleich die Schlüssel der englischen Tabelle.
public enum Sprache {
    public static let englisch: Bool = {
        if let erzwungen = ProcessInfo.processInfo.environment["ESPANSO_EDITOR_SPRACHE"] { return !erzwungen.hasPrefix("de") }
        let bevorzugt = Bundle.main.preferredLocalizations.first ?? Locale.preferredLanguages.first ?? "de"
        return !bevorzugt.hasPrefix("de")
    }()
}

/// Übersetzt einen deutschen Oberflächentext; `{0}`, `{1}` … werden durch die Argumente ersetzt.
public func L(_ text: String, _ argumente: Any...) -> String {
    var t = Sprache.englisch ? (Englisch.tabelle[text] ?? text) : text
    for (i, a) in argumente.enumerated() { t = t.replacingOccurrences(of: "{\(i)}", with: "\(a)") }
    return t
}

enum Englisch {
    static let tabelle: [String: String] = [
        // Allgemein / Seitenleiste / Tabelle
        "Alle": "All",
        "Ordner": "Folder",
        "Prüfen": "Check",
        "Kollisionen": "Collisions",
        "Doppelte Kürzel": "Duplicate abbreviations",
        "Kürzel ohne Wortgrenze, die mitten in echten Wörtern auslösen": "Abbreviations without word boundary that fire inside real words",
        "Neuer Ordner": "New Folder",
        "Neuer Ordner …": "New Folder…",
        "Neuer Baustein": "New Snippet",
        "Neuer Baustein (⌘N)": "New snippet (⌘N)",
        "Neuer Baustein hier": "New Snippet Here",
        "Umbenennen …": "Rename…",
        "Umbenennen": "Rename",
        "Ausschalten": "Switch Off",
        "Einschalten": "Switch On",
        "Ordner löschen": "Delete Folder",
        "Ordner umbenennen": "Rename Folder",
        "Aufbau nicht erkannt — nur lesen": "Structure not recognised — read only",
        "Name": "Name",
        "Anlegen": "Create",
        "Abbrechen": "Cancel",
        "Hinweis": "Note",
        "Kürzel": "Abbreviation",
        "Text": "Text",
        "Wortgrenze": "Word boundary",
        "Geändert": "Modified",
        "(neu)": "(new)",
        " (aus)": " (off)",
        "Kürzel kommt mehrfach vor": "Abbreviation is used more than once",
        "Löst mitten in Wörtern aus": "Fires inside words",
        "Löst nur als ganzes Wort aus": "Fires only as a whole word",
        "Löst auch mitten im Wort aus": "Also fires inside a word",
        "Verschieben nach": "Move to",
        "Wortgrenze an": "Word Boundary On",
        "Wortgrenze aus": "Word Boundary Off",
        "Duplizieren": "Duplicate",
        "Löschen": "Delete",
        "Keine Bausteine": "No snippets",
        "Nichts gefunden": "Nothing found",
        "⌘N legt einen neuen an.": "⌘N creates a new one.",
        "Auch ausgeschaltete Ordner durchsuchen? Schalter oben rechts.": "Also search folders that are switched off? Toggle at the top right.",
        "„{0}“ löschen?": "Delete “{0}”?",
        "{0} Bausteine löschen?": "Delete {0} snippets?",
        "Lässt sich über git zurückholen.": "Can be restored from git.",
        "Kürzel oder Text suchen": "Search abbreviation or text",
        "Kürzel suchen": "Search abbreviations",
        "Text suchen": "Search text",
        "Suchen in": "Search in",
        "Ganzes Wort": "Whole word",
        "Nur als ganzes Wort finden — „hgr“ findet dann nicht „hochgradig“": "Match whole words only — “hgr” then no longer finds “hochgradig”",
        "Suchen in Kürzel und Text, nur in Kürzeln oder nur im Text (Expansion)": "Search abbreviations and text, abbreviations only, or text (expansion) only",
        "Ausgeschaltete durchsuchen": "Search folders that are off",
        "Auch ausgeschaltete Ordner (z. B. Autokorrektur) durchsuchen": "Also search folders that are switched off (e.g. autocorrect)",
        "Noch kein Wortschatz und keine Schutzliste — unter Einstellungen › Kollisionen einrichten.": "No vocabulary and no protection list yet — set them up under Settings › Collisions.",
        "Wortgrenze setzen": "Set Word Boundary",
        "Keine Kollisionen": "No collisions",
        "So lassen": "Keep",
        "Schutzliste: {0}": "Protection list: {0}",
        "steckt in {0} ({1}× im Wortschatz)": "inside {0} ({1}× in vocabulary)",
        // Statusleiste
        "{0} aktiv · {1} gesamt": "{0} active · {1} total",
        "espanso lädt {0}": "espanso loads {0}",
        "espanso nicht gefunden": "espanso not found",
        "gesichert": "saved",
        "noch nicht verteilt": "not yet synced",
        "Wird nach 30 s Ruhe verteilt — jetzt: ⌘S": "Synced after 30 s of quiet — now: ⌘S",
        "wird verteilt …": "syncing…",
        "nicht verteilt": "not synced",
        "ohne git": "no git",
        "Schriftgrösse {0} pt — ⌘+ / ⌘− / ⌘0": "Font size {0} pt — ⌘+ / ⌘− / ⌘0",
        "Einstellungen": "Settings",
        // Editor
        "Kein Baustein ausgewählt": "No snippet selected",
        "{0} Bausteine ausgewählt": "{0} snippets selected",
        "In der Tabelle wählen oder mit ⌘N neu anlegen.": "Select one in the table or create one with ⌘N.",
        "Mit der Maus auf einen Ordner ziehen oder per Rechtsklick verschieben.": "Drag onto a folder or move them with a right click.",
        "Eintrag mit Variablen/Formular — als YAML bearbeiten (beginnt mit „- trigger:“).": "Entry with variables/form — edit as YAML (starts with “- trigger:”).",
        "Mehrere Kürzel mit Komma trennen": "Separate several abbreviations with commas",
        "An: löst nur als ganzes Wort aus (z. B. „dt“ nicht in „Stadtpark“)": "On: fires only as a whole word (e.g. “dt” not inside “Stadtpark”)",
        "Als YAML bearbeiten (Variablen, Formulare …)": "Edit as YAML (variables, forms…)",
        "Neu — wird gespeichert, sobald Kürzel und Text ausgefüllt sind.": "New — saved as soon as abbreviation and text are filled in.",
        "„{0}“ gibt es auch in „{1}“ — espanso nimmt dann einen davon.": "“{0}” also exists in “{1}” — espanso then uses one of them.",
        "„{0}“ gibt es auch in „{1}“ (+{2}) — espanso nimmt dann einen davon.": "“{0}” also exists in “{1}” (+{2}) — espanso then uses one of them.",
        "„{0}“ steht auch im ausgeschalteten Ordner „{1}“ — stört erst, wenn er eingeschaltet wird.": "“{0}” also exists in the switched-off folder “{1}” — only matters once it is switched on.",
        "Löst mitten in Wörtern aus: {0}": "Fires inside words: {0}",
        "LanguageTool nicht erreichbar — nur macOS-Prüfung": "LanguageTool unreachable — macOS check only",
        "LanguageTool: keine Fehler": "LanguageTool: no issues",
        "Ins Wörterbuch": "Add to Dictionary",
        "Ins Wörterbuch aufnehmen": "Add to Dictionary",
        "Ignorieren": "Ignore",
        "(entfernen)": "(remove)",
        "Rechtschreibung: macOS (Tippfehler). Kommas und Grammatik prüft LanguageTool — in den Einstellungen einschalten.": "Spelling: macOS (typos). LanguageTool checks commas and grammar — switch it on in Settings.",
        // Menüs
        "Importieren": "Import",
        "CSV …": "CSV…",
        "espanso-YAML …": "espanso YAML…",
        "Aus Typinator (laufende App)": "From Typinator (running app)",
        "Exportieren": "Export",
        "Sicherung als ZIP (espanso-Format) …": "Backup as ZIP (espanso format)…",
        "Tabelle als CSV …": "Table as CSV…",
        "Bausteine": "Snippets",
        "Jetzt verteilen": "Sync Now",
        "espanso neu starten": "Restart espanso",
        "Suchen": "Find",
        "Schrift grösser": "Bigger Text",
        "Schrift kleiner": "Smaller Text",
        "Normale Schriftgrösse": "Actual Size",
        // Import / Export
        "{0} Bausteine importieren": "Import {0} snippets",
        "Bereits vorhandene Kürzel werden übersprungen.": "Abbreviations that already exist are skipped.",
        "Ordner aus der Datei übernehmen": "Use folders from the file",
        "In „{0}“": "Into “{0}”",
        "Die Datei enthält keine Zeilen mit Kürzel und Text.": "The file contains no rows with abbreviation and text.",
        "Import abgeschlossen": "Import finished",
        "{0} neu, {1} übersprungen (Kürzel gab es schon).": "{0} new, {1} skipped (abbreviation already existed).",
        "{0} neu, {1} übersprungen (Kürzel gab es schon), {2} mit Typinator-Funktionen, die espanso nicht kennt.": "{0} new, {1} skipped (abbreviation already existed), {2} with Typinator functions espanso does not know.",
        "Import fehlgeschlagen": "Import failed",
        "Export fehlgeschlagen": "Export failed",
        "Bausteine-{0}.zip": "Snippets-{0}.zip",
        "Bausteine-{0}.csv": "Snippets-{0}.csv",
        "Kürzel;Text;Ordner;Wortgrenze": "Abbreviation;Text;Folder;Word boundary",
        "ja": "yes",
        "nein": "no",
        "Importiert": "Imported",
        // Einstellungen
        "Allgemein": "General",
        "Rechtschreibung": "Spelling",
        "espanso-Ordner": "espanso folder",
        "Bausteine liegen in": "Snippets live in",
        "espanso-Programm": "espanso binary",
        "nicht gefunden": "not found",
        "{0} — Änderungen werden nach 30 s Ruhe committet und gepusht": "{0} — changes are committed and pushed after 30 s of quiet",
        "kein git-Repo — Änderungen werden nur gespeichert": "no git repository — changes are only saved",
        "Jede Änderung ist nach ca. 1 s in espanso aktiv. Ausgeschaltete Ordner sind Dateien mit „_“ vorne — espanso lädt sie nicht.": "Every change is active in espanso about 1 s later. Folders that are off are files starting with “_” — espanso does not load them.",
        "macOS prüft immer die Rechtschreibung (rot unterstrichen). Kommas und Grammatik prüft es auf Deutsch nicht — dafür LanguageTool.": "macOS always checks spelling (red underline). It does not check commas and grammar in German — that is what LanguageTool is for.",
        "LanguageTool verwenden (Text wird an languagetool.org gesendet)": "Use LanguageTool (text is sent to languagetool.org)",
        "E-Mail (Premium-Konto)": "E-mail (Premium account)",
        "API-Schlüssel": "API key",
        "Sprache": "Language",
        "Automatisch (de-CH / en-GB)": "Automatic (de-CH / en-GB)",
        "Deutsch (Schweiz)": "German (Switzerland)",
        "Deutsch (Deutschland)": "German (Germany)",
        "Englisch (GB)": "English (UK)",
        "Englisch (US)": "English (US)",
        "Speichern & testen": "Save & Test",
        "Verbunden, aber nichts gemeldet": "Connected, nothing reported",
        "OK — {0} Hinweis(e): {1}": "OK — {0} issue(s): {1}",
        "Ohne E-Mail/Schlüssel wird die freie API genutzt (Zeichen- und Abfragegrenzen). Den Premium-Schlüssel gibt es im LanguageTool-Konto unter „Zugangsdaten“.": "Without e-mail/key the free API is used (character and request limits). The Premium key is in your LanguageTool account under “Credentials”.",
        "Schutzliste — ein Wort pro Zeile": "Protection list — one word per line",
        "Wörter, in denen kein Kürzel auslösen darf (z. B. VVR, Stadtpark). Liegt in match/_bausteine/ und wird mit den Bausteinen verteilt.": "Words no abbreviation may fire inside (e.g. product names). Stored in match/_bausteine/ and synced with the snippets.",
        "Wortschatz": "Vocabulary",
        "Datei": "File",
        "Wörter": "Words",
        "Aus Textdateien aufbauen …": "Build from Text Files…",
        "Andere Datei wählen …": "Choose Another File…",
        "Wörter, die du wirklich schreibst (z. B. aus alten Berichten). Bleibt lokal, wird nicht verteilt.": "Words you actually write (e.g. from old documents). Stays local, never synced.",
        "Textdateien oder Ordner mit Berichten wählen (txt, md, csv, jsonl)": "Choose text files or folders with documents (txt, md, csv, jsonl)",
        // Meldungen
        "Abgleich beim Start: {0}": "Sync at start: {0}",
        "espanso lädt nach dem Speichern {0} statt {1} Bausteine — Änderung zurückgenommen. Bitte den letzten Eintrag prüfen.": "After saving, espanso loads {0} instead of {1} snippets — change rolled back. Please check the last entry.",
        "Der YAML-Text von „{0}“ ist kein gültiger einzelner Eintrag (muss mit „- “ beginnen).": "The YAML of “{0}” is not a single valid entry (must start with “- ”).",
        "{0}: Die neu geschriebene Datei ergäbe nicht dieselben Bausteine — nicht gespeichert. ({1})": "{0}: the rewritten file would not contain the same snippets — not saved. ({1})",
        "{0} ist kein gültiges espanso-YAML: {1}": "{0} is not valid espanso YAML: {1}",
        "Abweichung bei „{0}“": "mismatch at “{0}”",
        "Aufbau nicht mehr lesbar": "structure no longer readable",
        "Aufbau nicht erkannt": "structure not recognised",
        "Typinator liess sich nicht auslesen: {0}": "Could not read Typinator: {0}",
        "LanguageTool antwortet mit {0}: {1}": "LanguageTool answered {0}: {1}",
        "gesichert (ohne Gegenstelle)": "saved (no remote)",
        "gesichert und verteilt": "saved and synced",
        "Abgleich: ": "Sync: ",
        // Commit-Protokoll
        "geändert: {0}": "changed: {0}",
        "dupliziert: {0}": "duplicated: {0}",
        "gelöscht: {0}": "deleted: {0}",
        "verschoben: {0} → {1}": "moved: {0} → {1}",
        "neuer Ordner: {0}": "new folder: {0}",
        "Ordner umbenannt: {0}": "folder renamed: {0}",
        "Ordner eingeschaltet: {0}": "folder switched on: {0}",
        "Ordner ausgeschaltet: {0}": "folder switched off: {0}",
        "Ordner gelöscht: {0}": "folder deleted: {0}",
        "Schutzliste": "protection list",
        "Kollision akzeptiert: {0}": "collision accepted: {0}",
        "importiert: {0} Bausteine": "imported: {0} snippets",
        "importiert: {0} aus {1}": "imported: {0} from {1}",
        "Änderungen": "changes",
    ]
}
